---
- name: Deploy S3 Static Website
  hosts: localhost
  vars:
    BUCKET_NAME: "sarahtav"
    BUCKET_REGION: "eu-west-3"
  tasks:
    - name: Installation du Bucket S3
      module:
        parametre: XX
    - name: Attach a policy the bucket
    - name: Set website configuration index/error file
    - name: create a index HTML page
    - name: synchronize the files
    - name: test the website
